markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.*
  - CNAME
  - deploy.ps1
  - run.ps1
  - .editorconfig

sass:
  style: compressed
  #style: expanded

# https://help.github.com/articles/repository-metadata-on-github-pages/
github: [metadata]
repository: ramastons/web

# Main Headline, name required, subtitle optional
name: Ramastons Rock Band
description: Ramastons website, a rock band based in El Vendrell, Tarragona

title: Ramastons
subtitle: Official Ramastons website

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
  description: Ramastons, a rock band based in El Vendrell, Tarragona
  keywords: rock, band, ramastons, el vendrell, tarragona, barcelona, feel alive, we believe this can be won, fender, telecaster, gibson, les paul
  crawl: index,follow

# website address when deployed, also given as canonical link
url: http://www.ramastons.com/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
baseurl: ''

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
  account: 'UA-63792232-1'
  cookieconsent: true
  anonymizeip: true

# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
avatar: '/assets/images/avatar.svg'

# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  -
    name: Spotify
    show: true
    href: https://open.spotify.com/artist/2be6NKWy1BnDea4eenXNQc
    icon: fab fa-spotify
  -
    name: Twitter
    show: true
    href: https://twitter.com/ramastons
    icon: fab fa-twitter
  -
    name: Facebook
    show: true
    href: https://facebook.com/ramastons
    icon: fab fa-facebook

youtube:
  embed:
    link: //www.youtube.com/embed/B-8tJ-1toBY

spotify:
  embed:
    link: https://open.spotify.com/embed/album/0kXGMndRGf5ZHH0ydAJswh
  artist:
    link: https://open.spotify.com/artist/2be6NKWy1BnDea4eenXNQc

carousel:
  -
    image: assets/images/banners/spotify-feel-alive-promo.png
    link: https://open.spotify.com/artist/2be6NKWy1BnDea4eenXNQc
    description: Ramastons on Spotify
  -
    image: assets/images/banda/ramastons-vinya-1.jpg
    link: #
    description: Ramastons
  -
    image: assets/images/banners/itunes-feel-alive-promo.png
    link: https://itunes.apple.com/es/album/feel-alive/id897965083
    description: Ramastons on Apple Music
  -
    image: assets/images/banners/google-play-feel-alive-promo.png
    link: https://play.google.com/store/music/artist/Ramastons?id=Aqr6nsnz7qwj7e22crwbdf6pspa&hl=ca
    description: Ramastons on Google Play
  -
    image: assets/images/banners/facebook-ramastons-promo.png
    link: https:/facebook.com/ramastons
    description: Ramastons Facebook
  -
    image: assets/images/banda/ramastons-vinya-2.jpg
    link: #
    description: Ramastons
  -
    image: assets/images/banda/ramastons-vinya-3.jpg
    link: #
    description: Ramastons

collections:
  pages:
    output: true
    permalink: /:path
